// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dqpylhwcdyzuqumzfran.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRxcHlsaHdjZHl6dXF1bXpmcmFuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM3ODY4NTIsImV4cCI6MjA2OTM2Mjg1Mn0.eGhMB3XB1oB9DoOBIrPtJ-23Iumss4Z0dzWc2nqGkwo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});